# Generated by Django 3.2.7 on 2021-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=500)),
                ('lastname', models.CharField(default='', max_length=500)),
                ('username', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=500)),
                ('zipcode', models.CharField(default='', max_length=500)),
                ('password', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
