# Generated by Django 3.2.7 on 2021-10-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211010_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
